#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not comply, but you have some other compliant shell available, you may
#       specify it by setting the SHELL variable when running this script.
#       For example: SHELL=/bin/bash ./gradlew
#
#   (2) Avoid modifying this script.
#
#   (3) If you want to use this script in a CI/CD pipeline, make sure it has
#       execute permissions.
#
##############################################################################

app_name="$0"
app_path=$(cd "$(dirname "$0")" || exit 1; pwd -P)

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn() {
    echo "$*" >&2
}

die() {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
esac

# Attempt to set APP_HOME
# Resolve links: $0 may be a symlink
PRG="$0"
# Need this for daisy-chained symlinks.
while [ -h "$PRG" ] ; do
    ls=$(ls -ld "$PRG")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=$(dirname "$PRG")"/"$link"
    fi
done
PRG=$(cd "$(dirname "$PRG")" || exit 1; pwd -P)
APP_HOME=$(dirname "$PRG")

# Find java.exe, or use JAVA_HOME.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
fi

if ! command -v java >/dev/null 2>&1
then
    die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$msys" ; then
    case $MAX_FD in #(
      /[0-9]*)
        MAX_FD=$( expr $MAX_FD ) ;; #(
      *)
        MAX_FD=max
        ;;
    esac
    ulimit -n $MAX_FD
fi

if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CP="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
    CP=$( cygpath --path --mixed "$CP" )
    CLASSPATH="${CP}"
    JAVACMD=$(cygpath --mixed "$JAVACMD")

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;; # don't mess with options #(
              /?*)  t=1 ;; # looks like a POSIX filepath
              *)    t=0 ;; # relative or something else
            esac
        then
            arg=$(cygpath --path --mixed "$arg")
        fi
        arg=$(printf '%s\n' "$arg" | sed "s/'/'\\\\''/g") # let Bash ownside effect variables unless running in POSIX mode
        CLASS="$CLASS$arg"
        case $arg in
          */)   trailing_slash=1 ;;
          *)    trailing_slash= ;;
        esac
    done
    case $CLASS in
      */)   CLASS="${CLASS%?}" ;;
    esac
    CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    if [ "$CLASSPATH" != "" ] ; then
        CLASSPATH="${CLASSPATH}:${CP}"
    else
        CLASSPATH="${CP}"
    fi
    if command -v cygpath > /dev/null; then
        CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
    fi

    JAVACMD=$(cygpath --mixed "$JAVACMD")

    # Workaround for when JAVA_HOME contains spaces.
    if [[ "$JAVACMD" == *\ * ]]; then
      CLASSPATH=$(echo "$CLASSPATH" | sed 's/ /\\ /g')
      JAVACMD=$(echo "$JAVACMD" | sed 's/ /\\ /g')
    fi
    # Now we can call Gradle encapsulated in double quotes and ${CLASSPATH}
    GRADLE_OPTS="${GRADLE_OPTS}"
    GRADLE_OPTS="${GRADLE_OPTS} -Dorg.gradle.appname=${0##*/}"
    exec "$JAVACMD" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
else
    # Unix/Linux
    CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

    # Workaround for when JAVA_HOME contains spaces.
    if [[ "$JAVACMD" == *\ * ]]; then
      CLASSPATH=$(echo "$CLASSPATH" | sed 's/ /\\ /g')
      JAVACMD=$(echo "$JAVACMD" | sed 's/ /\\ /g')
    fi

    # Now we can call Gradle encapsulated in double quotes and ${CLASSPATH}
    GRADLE_OPTS="${GRADLE_OPTS}"
    GRADLE_OPTS="${GRADLE_OPTS} -Dorg.gradle.appname=${0##*/}"
    exec "$JAVACMD" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
fi
